//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -c.
        /// </summary>
        internal static string Arg_Clipboard {
            get {
                return ResourceManager.GetString("Arg_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ctx-menu.
        /// </summary>
        internal static string Arg_CtxMenu {
            get {
                return ResourceManager.GetString("Arg_CtxMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p.
        /// </summary>
        internal static string Arg_Push {
            get {
                return ResourceManager.GetString("Arg_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -pa.
        /// </summary>
        internal static string Arg_PushAll {
            get {
                return ResourceManager.GetString("Arg_PushAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -send-to.
        /// </summary>
        internal static string Arg_SendTo {
            get {
                return ResourceManager.GetString("Arg_SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro.
        /// </summary>
        internal static string Reg_Shell {
            get {
                return ResourceManager.GetString("Reg_Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\First.
        /// </summary>
        internal static string Reg_Shell_First {
            get {
                return ResourceManager.GetString("Reg_Shell_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\First\command.
        /// </summary>
        internal static string Reg_Shell_First_Cmd {
            get {
                return ResourceManager.GetString("Reg_Shell_First_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\Main.
        /// </summary>
        internal static string Reg_Shell_Main {
            get {
                return ResourceManager.GetString("Reg_Shell_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\Main\command.
        /// </summary>
        internal static string Reg_Shell_Main_Cmd {
            get {
                return ResourceManager.GetString("Reg_Shell_Main_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\Second.
        /// </summary>
        internal static string Reg_Shell_Snd {
            get {
                return ResourceManager.GetString("Reg_Shell_Snd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\Second\command.
        /// </summary>
        internal static string Reg_Shell_Snd_Cmd {
            get {
                return ResourceManager.GetString("Reg_Shell_Snd_Cmd", resourceCulture);
            }
        }
    }
}
