//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Andro.Properties {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Andro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto.
        /// </summary>
        internal static string Arg_Auto {
            get {
                return ResourceManager.GetString("Arg_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clipboard.
        /// </summary>
        internal static string Arg_Clipboard {
            get {
                return ResourceManager.GetString("Arg_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integration.
        /// </summary>
        internal static string Arg_Integration {
            get {
                return ResourceManager.GetString("Arg_Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to push.
        /// </summary>
        internal static string Arg_Push {
            get {
                return ResourceManager.GetString("Arg_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to push-all.
        /// </summary>
        internal static string Arg_PushAll {
            get {
                return ResourceManager.GetString("Arg_PushAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro.
        /// </summary>
        internal static string Reg_Shell {
            get {
                return ResourceManager.GetString("Reg_Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\First.
        /// </summary>
        internal static string Reg_Shell_First {
            get {
                return ResourceManager.GetString("Reg_Shell_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\First\command.
        /// </summary>
        internal static string Reg_Shell_First_Cmd {
            get {
                return ResourceManager.GetString("Reg_Shell_First_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\Main.
        /// </summary>
        internal static string Reg_Shell_Main {
            get {
                return ResourceManager.GetString("Reg_Shell_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\Main\command.
        /// </summary>
        internal static string Reg_Shell_Main_Cmd {
            get {
                return ResourceManager.GetString("Reg_Shell_Main_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\Second.
        /// </summary>
        internal static string Reg_Shell_Snd {
            get {
                return ResourceManager.GetString("Reg_Shell_Snd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\Andro\shell\Second\command.
        /// </summary>
        internal static string Reg_Shell_Snd_Cmd {
            get {
                return ResourceManager.GetString("Reg_Shell_Snd_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/Andro.
        /// </summary>
        internal static string Url_Repo {
            get {
                return ResourceManager.GetString("Url_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/Andro/wiki.
        /// </summary>
        internal static string Url_Wiki {
            get {
                return ResourceManager.GetString("Url_Wiki", resourceCulture);
            }
        }
    }
}
